// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD73QGVyzRd_6xtBZ433pXWV85NTpFN0qA',
    appId: '1:797780920359:web:ed9d0e96d854997e53e602',
    messagingSenderId: '797780920359',
    projectId: 'rtsc-518fc',
    authDomain: 'rtsc-518fc.firebaseapp.com',
    storageBucket: 'rtsc-518fc.appspot.com',
    measurementId: 'G-VMWP1MZEZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD84El7k6H43o5tUmHDY7XE9wtYepdWcb8',
    appId: '1:797780920359:android:693d970c3c6912e153e602',
    messagingSenderId: '797780920359',
    projectId: 'rtsc-518fc',
    storageBucket: 'rtsc-518fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI2gKhdpL9WDcu2gLRw8QQVM9LwJoJErw',
    appId: '1:797780920359:ios:19da3c2be5ac2ea953e602',
    messagingSenderId: '797780920359',
    projectId: 'rtsc-518fc',
    storageBucket: 'rtsc-518fc.appspot.com',
    iosClientId: '797780920359-06ksdt5da440rb0aj042senes88nejam.apps.googleusercontent.com',
    iosBundleId: 'com.example.boxing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI2gKhdpL9WDcu2gLRw8QQVM9LwJoJErw',
    appId: '1:797780920359:ios:5aca3c01f9f6cb8d53e602',
    messagingSenderId: '797780920359',
    projectId: 'rtsc-518fc',
    storageBucket: 'rtsc-518fc.appspot.com',
    iosClientId: '797780920359-h8gtuqfh2jlrc8sueiprh3ed7qgkh20u.apps.googleusercontent.com',
    iosBundleId: 'com.example.boxing.RunnerTests',
  );
}
