// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLb1uxdBloS3tiA7Rma0jVAkSwnvtkOt4',
    appId: '1:881420286559:web:35eeaa261bb613e66b79ea',
    messagingSenderId: '881420286559',
    projectId: 'rtsc-live',
    authDomain: 'rtsc-live.firebaseapp.com',
    storageBucket: 'rtsc-live.appspot.com',
    measurementId: 'G-F4S4GW32ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8MNsR_kC7vOZOyxMUlWHAK_ERnYGA6yA',
    appId: '1:881420286559:android:b9685d56883c7c386b79ea',
    messagingSenderId: '881420286559',
    projectId: 'rtsc-live',
    storageBucket: 'rtsc-live.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF8F6vQTwi9oEA5iLTeGJtjZDUDdGlfpA',
    appId: '1:881420286559:ios:b25ec9dc791e46686b79ea',
    messagingSenderId: '881420286559',
    projectId: 'rtsc-live',
    storageBucket: 'rtsc-live.appspot.com',
    iosBundleId: 'live.rtsc.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF8F6vQTwi9oEA5iLTeGJtjZDUDdGlfpA',
    appId: '1:881420286559:ios:846071b9bedcffa16b79ea',
    messagingSenderId: '881420286559',
    projectId: 'rtsc-live',
    storageBucket: 'rtsc-live.appspot.com',
    iosBundleId: 'live.rtsc.app.RunnerTests',
  );
}
